---
- name: Pre-requistes
  hosts: all
  become_user: root
  become: yes
  
  tasks:
  - name: Update apt
    apt:
      update_cache: yes
  - name: Upgrade
    apt:
      upgrade: dist
  - name: Install pre-requisuite packages
    apt:
        name: "{{ packages }}"
    vars:
      packages:
        - postgresql
        - postgresql-contrib
        - python-psycopg2
        - python-pip
        - docker.io
        - ldapscripts
        - nginx
        - git
    become: yes
  - name: Pip install python dependency
    pip: 
      name: psycopg2
- name: MatterMost database maintenance as postgres
  hosts: all
  become: yes
  become_user: postgres
  tasks: 
  - name: Create MatterMost database
    postgresql_db:
      name: MatterMost
  - name: Create MatterMost user for database
    postgresql_user:
      db: MatterMost
      name: mmuser
      password: thisspaceforrent
      priv: ALL  
- name: Resume provisoining as root
  hosts: all
  become: yes
  become_user: root  
  tasks:
    - name: Setup pg_hba.conf
      postgresql_pg_hba:
        dest: /etc/postgresql/10/main/pg_hba.conf
        contype: local
        method: trust
    - name: Reload Postgresql
      service:
        name: postgresql
        state: reloaded
    - name: Get MM package and extract
      shell: |
        wget https://releases.mattermost.com/5.27.0/mattermost-5.27.0-linux-amd64.tar.gz
        tar -xvzf mattermost*.gz     
    - name: Staging all required configurations and certificates
      become_user: root
      shell: |
        mv mattermost /opt
        mkdir /opt/mattermost/data
        useradd --system --user-group mattermost
        chown -R mattermost:mattermost /opt/mattermost
        chmod -R g+w /opt/mattermost
        cp /vagrant/config.json /opt/mattermost/config/config.json
        chown -R mattermost:mattermost /opt/mattermost/config/config.json
        cp /vagrant/license /opt/mattermost/license
        chown -R mattermost:mattermost /opt/mattermost/license
        cp /vagrant/localhost.crt /etc/ssl/certs/localhost.crt
        cp /vagrant/localhost.key /etc/ssl/private/localhost.key
    - name: Make MatterMost a service and start it 
      become_user: root
      shell: |
        cp /vagrant/mattermost.service /lib/systemd/system/mattermost.service
        systemctl daemon-reload
        systemctl start mattermost.service
        systemctl enable mattermost.service
    - name: Setup docker container for LDAP
      become_user: root
      shell: | 
        docker pull rroemhild/test-openldap
        docker run --privileged -d -p 389:389 rroemhild/test-openldap
    - name: Setup users for for Planet Express
      become_user: root
      shell: | 
        cd /opt/mattermost
        bin/mattermost user create --email admin@planetexpress.com --username admin --password AdminAdmin1! --system_admin
        bin/mattermost team create --name planet-express --display_name "Planet Express" --email "admin@planetexpress.com"
        bin/mattermost team create --name olympus --display_name "Administrative Staff" --email "admin@planetexpress.com"
        bin/mattermost team create --name ship-crew --display_name "Ship's Crew" --email "admin@planetexpress.com"
        bin/mattermost team add planet-express admin@planetexpress.com
        bin/mattermost team add olympus admin@planetexpress.com
    - name: Setting up nginx reverse proxy
      become_user: root
      shell: | 
        cp /vagrant/mattermost /etc/nginx/sites-available/mattermost
        ln -s /etc/nginx/sites-available/mattermost /etc/nginx/sites-enabled/mattermost
    - name: Restarting nginx
      become_user: root  
      shell: 
        systemctl restart nginx


    